//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snackautomaten_Verwaltungsapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTROLLE
    {
        public System.DateTime KON_DATUM { get; set; }
        public int KON_A_ID { get; set; }
        public string KON_KOMMENT { get; set; }
        public int KON_ID { get; set; }
    
        public virtual AUTOMATEN AUTOMATEN { get; set; }
    }
}
