//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snackautomaten_Verwaltungsapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION
    {
        public int POS_ID { get; set; }
        public int POS_A_ID { get; set; }
        public int POS_P_ID { get; set; }
        public bool POS_LEER { get; set; }
    
        public virtual AUTOMATEN AUTOMATEN { get; set; }
        public virtual PRODUKT PRODUKT { get; set; }
    }
}
