//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snackautomaten_Verwaltungsapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class STANDORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STANDORT()
        {
            this.AUTOMATENs = new HashSet<AUTOMATEN>();
        }
    
        public int S_ID { get; set; }
        public string S_NAME { get; set; }
        public string S_BEZ { get; set; }
        public string S_ADRESSE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTOMATEN> AUTOMATENs { get; set; }
    }
}
